const express = require('express');
const { protect } = require('../middleware/auth');
const fc = require('../controllers/featureControllers');
const router = express.Router();
router.use(protect);
router.post('/register', fc.registerPushToken);
router.get('/', fc.getNotifications);
router.patch('/:notificationId/read', fc.markRead);
router.patch('/read-all', fc.markAllRead);
module.exports = router;
